### ISSUE TITLE
Spigot plugin but category is bungee ;p 

### ISSUE THREAD

**Issue by TymekSL** [Niix-Dan/ConsoleDiscord#3]
[19:56:21 INFO]: Loaded plugin RoleSync version 1.2.0-BETA-1.3 by dode5656
[19:56:21 WARN]: Error loading plugin ConsoleDiscord
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:301) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 13 more

**Comment by Niix-Dan** [comment]
Currently i'm working on updates and i will fix it soon, for now it's only available for spigot
